#!/usr/bin/env python3
"""
Fetch tick history from the current tick.edcd.io API and produce:
  1. A MySQL import SQL file (tick_history.sql)
  2. The static JSON files for the new deployment (api/tick, api/ticks)

Usage:
    python3 import-tick-history.py

Outputs (in the current directory):
    tick_history.sql  - MySQL INSERT statements for the ticks table
    api_tick.json     - Content for /api/tick (latest tick timestamp)
    api_ticks.json    - Content for /api/ticks (full history array)
"""

import json
import urllib.request
import sys


def fetch_ticks():
    """Fetch all ticks from the current tick.edcd.io API."""
    url = "https://tick.edcd.io/api/ticks?start=2014-12-16"
    print(f"Fetching tick history from {url}...")

    req = urllib.request.Request(url)
    req.add_header("User-Agent", "TickDetector-Migration/1.0")

    with urllib.request.urlopen(req, timeout=120) as response:
        data = json.loads(response.read().decode("utf-8"))

    print(f"Fetched {len(data)} ticks.")
    return data


def generate_sql(ticks):
    """Generate MySQL import SQL from tick data."""
    lines = []
    lines.append("-- Tick history imported from tick.edcd.io")
    lines.append("-- Generated by import-tick-history.py")
    lines.append("")
    lines.append("CREATE TABLE IF NOT EXISTS `ticks` (")
    lines.append("  `time` VARCHAR(30) NOT NULL,")
    lines.append("  PRIMARY KEY (`time`)")
    lines.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    lines.append("")
    lines.append("INSERT INTO `ticks` (`time`) VALUES")

    values = []
    for tick in ticks:
        timestamp = tick["TIME"].replace("'", "\\'")
        values.append(f"  ('{timestamp}')")

    lines.append(",\n".join(values) + ";")
    lines.append("")

    return "\n".join(lines)


def generate_api_tick(ticks):
    """Generate the /api/tick content (just the latest timestamp in quotes)."""
    if not ticks:
        return '"unknown"'
    # Ticks are ordered chronologically, latest is last
    latest = ticks[-1]["TIME"]
    return json.dumps(latest)


def generate_api_ticks(ticks):
    """Generate the /api/ticks content (full JSON array)."""
    return json.dumps(ticks, indent=None)


def main():
    ticks = fetch_ticks()

    if not ticks:
        print("No ticks found. Exiting.")
        sys.exit(1)

    # Sort by time to ensure correct ordering
    ticks.sort(key=lambda t: t["TIME"])

    # Generate SQL import file
    sql = generate_sql(ticks)
    with open("tick_history.sql", "w") as f:
        f.write(sql)
    print(f"Written: tick_history.sql ({len(ticks)} records)")

    # Generate static API files
    api_tick = generate_api_tick(ticks)
    with open("api_tick.json", "w") as f:
        f.write(api_tick)
    print(f"Written: api_tick.json (latest: {api_tick})")

    api_ticks = generate_api_ticks(ticks)
    with open("api_ticks.json", "w") as f:
        f.write(api_ticks)
    print(f"Written: api_ticks.json ({len(ticks)} entries)")

    print("\nDone. To import into MySQL:")
    print("  mysql -h <rds-host> -u <user> -p <database> < tick_history.sql")


if __name__ == "__main__":
    main()
